apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ecommerce-backend
  name: ecommerce-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ecommerce-backend
    spec:
      containers:
      - image: xocbayar/ecommerce-backend
        name: ecommerce-backend
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ecommerce-backend
  name: ecommerce-backend
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ecommerce-backend
  type: LoadBalancer
status:
  loadBalancer: {}
